spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "test": "common"
      "dev_aws": "dev_aws,common"
    include: core
    active: local
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    software.amazon.awssdk: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
        type:
          descriptor:
            sql: trace
---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: "common"
  application:
    name: petcare
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        query:
          in_clause_parameter_padding: true
        jdbc:
          time_zone: UTC
        default_batch_fetch_size: 100
firebase:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-multicast-message-size: 500
springdoc:
  swagger-ui:
    doc-expansion: "none"
    display-request-duration: true
    default-models-expand-depth: -1
    show-extensions: true
    persist-authorization: true
    default-model-expand-depth: 3
    operations-sorter: "method"
  override-with-generic-response: true
  writer-with-default-pretty-printer: true
secretKey : biskit23fa3fa3fw3fFAASqwdqsa1232
apiPrefix: v1
